// <auto-generated />
namespace SendSMSHost.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class import_without_contact : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(import_without_contact));
        
        string IMigrationMetadata.Id
        {
            get { return "201804041329086_import_without_contact"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
