// <auto-generated />
namespace SendSMSHost.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class expliciete_FK_verwijderd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(expliciete_FK_verwijderd));
        
        string IMigrationMetadata.Id
        {
            get { return "201806161248382_expliciete_FK_verwijderd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
