// <auto-generated />
namespace SendSMSHost.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Index_Logs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Index_Logs));
        
        string IMigrationMetadata.Id
        {
            get { return "201806192121096_Index_Logs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
